version: '3.8'
services:
  backend:
    build: ./backend
    container_name: gestion_activos_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - database_volume:/app/database
    environment:
      NODE_ENV: development
      DB_PATH: /app/database/gestion_activos.db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: gestion_activos_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  database_volume:

networks:
  app-network:
    driver: bridge
